services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    container_name: app
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ../app/:/lobby_service/app/
    networks:
      - backend
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"


networks:
  backend:
    driver: bridge

