services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    container_name: app
    env_file:
      - ../.env.example
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../app/:/app/
    networks:
      - backend
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"


networks:
  backend:
    driver: bridge

