services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: prod
    container_name: app
    env_file:
      - ../.env
      - ../.env.example
    ports:
      - "8000:8000"
    networks:
      - backend
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"


networks:
  backend:
    driver: bridge
